# Generated by Django 4.1.5 on 2023-01-29 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
    ]
